# wrangler.toml
name = "tokenist-dev"
compatibility_date = "2025-02-21"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_URL="https://api.tokenist.dev"
NEXT_PUBLIC_DASHBOARD_URL="https://dashboard.tokenist.dev"